inherit_from:
  - https://raw.githubusercontent.com/standout/Coding/master/ruby/rubocop.yml

Metrics/LineLength:
  Exclude:
    - "app/channels/application_cable/channel.rb"
    - "app/channels/application_cable/connection.rb"
    - "config/application.rb"
    - "config/environments/*.rb"
    - "config/initializers/*.rb"
    - "config/puma.rb"
    - "db/migrate/*.rb"
    - "db/seeds.rb"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"

Style/AlignParameters:
  Enabled: false

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

Style/BracesAroundHashParameters:
  Enabled: false

Style/EmptyLines:
  Exclude:
    - "config/environments/*.rb"

Style/IndentArray:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SpaceInsideBrackets:
  Exclude:
    - "config/environments/*.rb"
